PRAGMA foreign_keys = ON;
CREATE TABLE workspaces (id TEXT PRIMARY KEY, created_at INTEGER NOT NULL, expires_at INTEGER NOT NULL, settings_json TEXT NOT NULL DEFAULT '{}');
CREATE TABLE participants (id TEXT PRIMARY KEY, workspace_id TEXT NOT NULL REFERENCES workspaces(id), role TEXT NOT NULL CHECK(role IN ('admin','nurse','caller')), created_at INTEGER NOT NULL);
CREATE TABLE sessions (token_hash TEXT PRIMARY KEY, workspace_id TEXT NOT NULL, participant_id TEXT NOT NULL, role TEXT NOT NULL, expires_at INTEGER NOT NULL);
CREATE INDEX sessions_expiry ON sessions(expires_at);
CREATE TABLE invitations (token_hash TEXT PRIMARY KEY, workspace_id TEXT NOT NULL, role TEXT NOT NULL, expires_at INTEGER NOT NULL, redeemed_by TEXT);
CREATE TABLE template_versions (id TEXT NOT NULL, workspace_id TEXT NOT NULL, version INTEGER NOT NULL, body_json TEXT NOT NULL, created_at INTEGER NOT NULL, PRIMARY KEY(workspace_id,id,version));
CREATE TABLE call_initializations (workspace_id TEXT NOT NULL, participant_id TEXT NOT NULL, command_id TEXT NOT NULL, call_id TEXT NOT NULL UNIQUE, created_at INTEGER NOT NULL, PRIMARY KEY(workspace_id,participant_id,command_id));
CREATE TABLE calls (id TEXT PRIMARY KEY, workspace_id TEXT NOT NULL, caller_participant_id TEXT NOT NULL, created_at INTEGER NOT NULL, expires_at INTEGER NOT NULL, queue_state TEXT NOT NULL, intake_state TEXT NOT NULL, conversation_owner TEXT NOT NULL, revision INTEGER NOT NULL, snapshot_json TEXT NOT NULL, updated_at INTEGER NOT NULL);
CREATE INDEX calls_workspace_queue ON calls(workspace_id,queue_state,created_at);
CREATE TABLE transcript_segments (id TEXT NOT NULL, call_id TEXT NOT NULL, workspace_id TEXT NOT NULL, body_json TEXT NOT NULL, PRIMARY KEY(call_id,id));
CREATE TABLE intake_facts (field TEXT NOT NULL, call_id TEXT NOT NULL, workspace_id TEXT NOT NULL, revision INTEGER NOT NULL, body_json TEXT NOT NULL, PRIMARY KEY(call_id,field));
CREATE TABLE fact_revisions (id TEXT NOT NULL, call_id TEXT NOT NULL, workspace_id TEXT NOT NULL, body_json TEXT NOT NULL, PRIMARY KEY(call_id,id));
CREATE TABLE nurse_assignments (id TEXT NOT NULL, call_id TEXT NOT NULL, workspace_id TEXT NOT NULL, body_json TEXT NOT NULL, PRIMARY KEY(call_id,id));
CREATE TABLE escalation_events (id TEXT NOT NULL, call_id TEXT NOT NULL, workspace_id TEXT NOT NULL, body_json TEXT NOT NULL, PRIMARY KEY(call_id,id));
CREATE TABLE audit_events (id TEXT NOT NULL, call_id TEXT NOT NULL, workspace_id TEXT NOT NULL, revision INTEGER NOT NULL, body_json TEXT NOT NULL, PRIMARY KEY(call_id,id));
CREATE TABLE projection_checkpoints (call_id TEXT PRIMARY KEY, workspace_id TEXT NOT NULL, revision INTEGER NOT NULL DEFAULT 0, updated_at INTEGER NOT NULL);
CREATE TABLE deletion_tombstones (call_id TEXT PRIMARY KEY, workspace_id TEXT NOT NULL, deleted_at INTEGER NOT NULL);
CREATE TABLE exports (id TEXT PRIMARY KEY, call_id TEXT NOT NULL, workspace_id TEXT NOT NULL, object_key TEXT NOT NULL, status TEXT NOT NULL, expires_at INTEGER NOT NULL);
CREATE TABLE rate_limits (key TEXT PRIMARY KEY, window_start INTEGER NOT NULL, count INTEGER NOT NULL);
CREATE TABLE audio_reservations (call_id TEXT PRIMARY KEY, workspace_id TEXT NOT NULL, day TEXT NOT NULL, minutes INTEGER NOT NULL, expires_at INTEGER NOT NULL, released INTEGER NOT NULL DEFAULT 0);
