"use client";

import { RECORDING_DISCLOSURE, RECORDING_DISCLOSURE_VERSION, type DemoSettings, type IntakeTemplate } from "@nursebridge/contracts";
import { useEffect, useState } from "react";
import { Icon } from "./icons";
import { api, AuthGate, Badge, errorMessage, mutate, Notice, PageHeader, useWorkspace } from "./workspace";

export function SettingsPage() { return <AuthGate callerAllowed={false}><SettingsWorkspace /></AuthGate>; }
function SettingsWorkspace() {
  const { session } = useWorkspace();
  const admin = session?.role === "admin";
  const [settings, setSettings] = useState<DemoSettings | null>(null);
  const [template, setTemplate] = useState<IntakeTemplate | null>(null);
  const [destination, setDestination] = useState("");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [saved, setSaved] = useState<string | null>(null);
  const [editTemplate, setEditTemplate] = useState(false);
  const apply = (value: DemoSettings) => { setSettings(value); setTemplate(value.template); setDestination(value.escalationDestination); };
  useEffect(() => { void api<DemoSettings>("/api/settings").then(apply).catch((reason) => setError(errorMessage(reason))); }, []);
  const save = async (publish: boolean) => {
    if (!settings || !template) return;
    setBusy(true); setError(null); setSaved(null);
    try {
      const value = await mutate<DemoSettings>("/api/settings", publish ? { template } : { escalationDestination: destination }, "PATCH");
      setSettings(value);
      if (publish) { setTemplate(value.template); setEditTemplate(false); }
      else { setDestination(value.escalationDestination); if (!editTemplate) setTemplate(value.template); }
      setSaved(publish ? `Template version ${value.template.version} published for new calls. Active calls retain their original template.` : "Workspace settings saved.");
    } catch (reason) { setError(errorMessage(reason)); } finally { setBusy(false); }
  };
  const toggleTemplateEditor = () => { if (!settings) return; setTemplate(settings.template); setEditTemplate((editing) => !editing); };
  return <div className="page settings-page"><PageHeader eyebrow="WORKSPACE CONFIGURATION" title="A consistent starting point." description="Approved prompts, explicit boundaries, and provider visibility." action={<Badge tone={admin ? "teal" : "neutral"}>{admin ? "Workspace administrator" : "Read-only staff access"}</Badge>} />
    {error && <Notice kind="error">{error}</Notice>}{saved && <Notice>{saved}</Notice>}{!admin && <Notice>Only authorized workspace administrators can publish templates or edit settings.</Notice>}
    {!settings || !template ? <section className="panel"><div className="empty-state" role="status">{error ? "Settings could not be loaded." : "Loading workspace settings…"}</div></section> : <div className="settings-grid"><div><section className="panel settings-section"><div className="panel-heading"><h2>Intake template</h2><Badge tone="teal">VERSION {settings.template.version}</Badge></div><div className="panel-content"><div className="row between" style={{ marginBottom: 7 }}><h3>{settings.template.name}</h3>{admin && <button className="text-link" disabled={busy} onClick={toggleTemplateEditor}>{editTemplate ? "Cancel editing" : "Create next version"}</button>}</div><p className="template-meta">New versions apply to new calls. Each active call retains its approved template.</p>{editTemplate ? <form className="form-grid" onSubmit={(event) => { event.preventDefault(); void save(true); }}><div><label className="field-label" htmlFor="template-name">Template name</label><input className="text-input" id="template-name" maxLength={100} required disabled={busy} value={template.name} onChange={(event) => setTemplate({ ...template, name: event.target.value })} /></div><div><label className="field-label" htmlFor="template-opening">Approved opening question</label><textarea className="text-input" id="template-opening" maxLength={500} required disabled={busy} value={template.opening} onChange={(event) => setTemplate({ ...template, opening: event.target.value })} /></div>{template.questions.map((question, index) => <div key={question.id}><label className="field-label" htmlFor={`question-${question.id}`}>{question.field.replace(/_/g, " ")}</label><input className="text-input" id={`question-${question.id}`} maxLength={500} required disabled={busy} value={question.text} onChange={(event) => setTemplate({ ...template, questions: template.questions.map((item, number) => number === index ? { ...item, text: event.target.value } : item) })} /></div>)}<Notice kind="warning">Approved wording must collect patient-reported information only. Do not introduce diagnosis, treatment, reassurance, or advice that waiting is safe.</Notice><button className="button primary" disabled={busy} type="submit">Publish next template version</button></form> : <><div className="approved-copy">“{settings.template.opening}”</div><div style={{ marginTop: 13 }}>{settings.template.questions.map((question, index) => <div className="template-question" key={question.id}><span>{String(index + 1).padStart(2, "0")}</span><span>{question.text}</span></div>)}</div><p className="fine-print" style={{ marginTop: 16 }}>The assistant asks one missing question at a time. After one unsuccessful clarification, uncertainty stays visible for the nurse.</p></>}</div></section>
      <section className="panel settings-section"><div className="panel-heading"><h2>Inbound phone calls</h2><Badge tone={settings.phoneInbound?.enabled && settings.phoneInbound.configured ? "teal" : "amber"}>{settings.phoneInbound?.enabled && settings.phoneInbound.configured ? "Configuration present" : "Needs setup"}</Badge></div><div className="panel-content"><div className="setting-line"><div><strong>Twilio phone → browser nurse</strong><p>Phone callers enter this workspace’s queue when an operator routes a number here. Take over and speak using the same nurse call controls.</p></div></div><p className="fine-print">Automated intake requires separate caller consent and verified provider activation. When it is unavailable, callers can still wait for a nurse. Phone callers can press 0 to request a person.</p>{admin && <div style={{ marginTop: 14 }}><label className="field-label" htmlFor="phone-workspace">Workspace ID for phone routing</label><input className="text-input" id="phone-workspace" readOnly value={session?.workspaceId || ""} /><p className="field-hint">Give this ID to the deployment operator. Phone numbers and account secrets are configured on the server. This workspace expires after seven days; keep an active staff session or invitation to return.</p></div>}<p className="fine-print" style={{ marginTop: 12 }}>Configuration does not confirm a working telephone call. Test the connected number before sharing it. Do not enter patient information before release approval.</p></div></section>
      <section className="panel settings-section"><div className="panel-heading"><h2>Approved boundaries</h2><Icon name="file" size={17} /></div><div className="panel-content"><div className="approved-copy">“Clinical use requires completed release approval. Do not enter patient information.”</div><div className="section-divider" /><div className="setting-line"><div><strong>Assistant identity</strong><p>An automated intake assistant, not a nurse.</p></div></div><div className="setting-line"><div><strong>Intake completion</strong><p>“Intake captured — awaiting nurse assessment.”</p></div></div><div className="setting-line"><div><strong>Emergency limitations</strong><p>NurseBridge does not provide emergency care. Real emergencies require contacting emergency services. No automatic emergency calls.</p></div></div><div className="setting-line"><div><strong>Human access</strong><p>Consent refusal, incomplete intake and provider failure never remove a caller from the queue.</p></div></div></div></section></div>
      <div><section className="panel settings-section"><div className="panel-heading"><h2>Provider connectivity</h2><Badge tone={settings.mode === "mock" ? "amber" : "teal"}>{settings.mode.toUpperCase()} MODE</Badge></div><div className="panel-content">{([ ["voiceAgent", "A", "AssemblyAI Voice Agent", "Streaming conversation, speech and consented provider recording"], ["extraction", "N", "Nebius Token Factory", "Nemotron-3.5-Lightning · evidence-validated extraction"] ] as const).map(([key, letter, label, detail]) => { const provider = settings.providers[key]; return <div className="provider-line" key={key}><span className="provider-letter">{letter}</span><div style={{ flex: 1 }}><h3>{label}</h3><p>{detail}</p><p>{settings.mode === "mock" ? "Explicit fixture adapter; no live integration claim." : provider.verified ? "Provider connection verified." : provider.configured ? "Configuration present; live operation not yet verified." : "Required live intake configuration is missing."}</p></div><Badge tone={settings.mode === "mock" || !provider.verified ? "amber" : "teal"}>{settings.mode === "mock" ? "Fixture" : provider.verified ? "Verified" : provider.configured ? "Configured" : "Missing"}</Badge></div>; })}<p className="fine-print" style={{ borderTop: "1px solid var(--line)", marginTop: 18, paddingTop: 13 }}>Configuration is not evidence of a successful live call. Provider warnings remain visible in the case.</p></div></section>
      <section className="panel settings-section"><div className="panel-heading"><h2>Human-request destination</h2><Icon name="person" size={17} /></div><form className="panel-content" onSubmit={(event) => { event.preventDefault(); void save(false); }}><label className="field-label" htmlFor="escalation-destination">Staff destination</label><input className="text-input" id="escalation-destination" value={destination} onChange={(event) => setDestination(event.target.value)} disabled={!admin || busy} maxLength={120} required /><p className="field-hint">A visible destination label for this workspace. It does not connect to a real clinic or send an emergency alert.</p><div className="section-divider" /><p className="fine-print">Human requests and technical failures require visible staff acknowledgment. This workflow is not a clinical escalation protocol.</p>{admin && <div className="settings-actions"><button className="button primary small" disabled={busy || !destination.trim() || destination === settings.escalationDestination} type="submit">Save destination</button></div>}</form></section>
      <section className="panel settings-section"><div className="panel-heading"><h2>Privacy defaults</h2><Icon name="file" size={17} /></div><div className="panel-content"><div className="setting-line"><div><strong>Automated-intake recording</strong><p>{settings.mode === "mock" ? "Transcript replay does not use AssemblyAI recording." : settings.recording.enabled ? RECORDING_DISCLOSURE : "AssemblyAI recording is disabled for this deployment."}</p>{settings.mode === "live" && <p className="fine-print">Disclosure {settings.recording.disclosureVersion || RECORDING_DISCLOSURE_VERSION} · provider retention verified: {settings.recording.retentionVerified ? "yes" : "no"} · deletion controls verified: {settings.recording.deletionVerified ? "yes" : "no"}</p>}</div><span className="toggle-static">{settings.mode === "live" && settings.recording.enabled ? "CONSENT" : "OFF"}</span></div><div className="setting-line"><div><strong>Human takeover</strong><p>After takeover, caller and nurse audio bypass automated intake providers.</p></div></div><div className="setting-line"><div><strong>Case retention</strong><p>Case records expire after {settings.retentionDays} days. Backup and provider retention can differ from active case deletion.</p></div><span className="toggle-static">{settings.retentionDays} DAYS</span></div><div className="setting-line"><div><strong>Private exports</strong><p>Explicitly requested JSON/Markdown exports require authorization and have limited retention.</p></div></div><div className="setting-line"><div><strong>Browser storage</strong><p>Case content is not stored in localStorage.</p></div></div><div className="setting-line"><div><strong>Clinical use</strong><p>Clinical use requires completed identity, privacy, and operational validation.</p></div><Badge tone="amber">PRE-PRODUCTION</Badge></div></div></section></div></div>}
  </div>;
}
